version: "2" # required to adjust maintainability checks
checks:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 75
  file-lines:
    config:
      threshold: 500
  method-lines:
    config:
      threshold: 75
exclude_patterns:
  - "dist/"
  - "**/node_modules/"
  - "**/spec/"
  - "**/test/"
  - "**/__spec__/"
  - "**/__spec__/**"
  - "**/__tests__/"
  - "**/__tests__/**"
  - "**/tests/"
  - "Tests/"
  - "*.spec.js"
  - "**/*.spec.js"
  - "**/tmp/**"
